# Independent settings for the planner's costmap
global_costmap:
  map_type: costmap

  # NOTE: 'global_frame' is overwritten by .launch file
  global_frame: map
  # NOTE: 'robot_base_frame' is overwritten by .launch file
  robot_base_frame: base_footprint

  update_frequency: 10.0
  publish_frequency: 1.0

  transform_tolerance: 0.2

  track_unknown_space: true
  unknown_cost_value: 255

  robot_radius: 0.275

  # plugins are loaded in a separate file

  static_layer:
    enabled: true
    # NOTE: 'map_topic' is overwritten by .launch file
    map_topic: map

  obstacle_laser_layer:
    enabled: true
    observation_sources: base_scan
    # can erase static layer
    combination_method: 0

    base_scan:
      # NOTE: 'sensor_frame' is overwritten by .launch file
      sensor_frame: base_laser_link
      data_type: LaserScan
      # NOTE: 'topic' is overwritten by .launch file
      topic: scan
      expected_update_rate: 0.3
      observation_persistence: 1.0
      inf_is_valid: true
      marking: true
      clearing: true
      raytrace_range: 4.0
      obstacle_range: 3.0

  obstacle_rgbd_layer:
    enabled: true
    observation_sources: rgbd_scan
    combination_method: 1

    rgbd_scan:
      # NOTE: 'sensor_frame' is overwritten by .launch file
      sensor_frame: base_footprint
      data_type: LaserScan
      # NOTE: 'topic' is overwritten by .launch file
      topic: rgbd_scan
      expected_update_rate: 0.5
      observation_persistence: 0.0
      inf_is_valid: true
      marking: true
      clearing: true
      raytrace_range: 3.5
      obstacle_range: 3.2
      blanking_range: 0.5
      min_obstacle_height: -0.1
      max_obstacle_height: 0.2
      debug: true

  inflation_layer:
    enabled: true
    inflation_radius: 0.55
    cost_scaling_factor: 25.0
