planner_frequency: 1.0
planner_patience: 5.0

controller_frequency: 2.0
controller_patience:  10.0

oscillation_timeout: 20.0
oscillation_distance:  0.2

recovery_behavior_enabled: true
shutdown_costmaps: false

search_alternative_goals: true
alternative_goals_thresh: 1.5
latch_xy_goal_tolerance: true
