recovery_behaviors:
  - name: 'costmap_reset_far'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'costmap_reset_close'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'
  - name: 'costmap_reset'
    type: 'clear_costmap_recovery/ClearCostmapRecovery'

costmap_reset_far:
  reset_distance: 3.0
  layer_names: "obstacle_laser_layer" #, "obstacle_rgbd_layer"]

costmap_reset_close:
  reset_distance: 1.5
  layer_names: "obstacle_laser_layer" #, "obstacle_rgbd_layer"]

costmap_reset:
  reset_distance: 0.0
  layer_names: "obstacle_laser_layer" #, "obstacle_rgbd_layer"]
