initialization:

    # if not set - will be random within world bounds
    pose: [1.0, 1.0, 0.0, 0.0, 0.0, 0.75]   # {x, y, z, r, p, y}
    stance: 1                               # look for core/Enums.h

general:

    bounding_type: 2                    # look for core/Enums.h
    animation_factor: 4.5               # how fast the animation is played
    animation_speed_rotation: 0.007     # dist_traveled
    target_tolerance: 1.25              # in meters
    target_reach_max_time: 60.0         # in seconds
    target_reachable_check_period: 2.0  # in seconds
    world_bound_x: [-3.20, +3.80]       # in meters, actor will not be allowed to move further along X axis
    world_bound_y: [-10.20, +3.80]      # in meters, actor will not be allowed to move further along X axis