plugins: 
  - {name: static_layer, type: "costmap_2d::StaticLayer"}
  - {name: inflation_layer, type: "costmap_2d::InflationLayer"}

# ---- Coordinate frame and tf
global_frame: "world"
robot_base_frame: "map"      # NOTE: it must be valid at the startup, otherwise node will never start global planner srv
transform_tolerance: 1.0        # def 0.5

# ---- Rate
update_frequency:  2.0           # 1.0
publish_frequency: 5.0           # 0.5

# ---- Map management
rolling_window: false            # can't be true if static_map is used
map_type: costmap
always_send_full_costmap: true
static_map: true
publish_potential: true

# ---- Footprint
# robot's not circular
footprint: [[0.3, -0.15], [0.3, +0.15], [-0.3, +0.15], [-0.3, -0.15]] 
footprint_padding: 0.05
#default_tolerance: 0.20   # X cm of gap allowed