# ---- Inflation
# inflation_layer:
  inflation_radius: 0.2    # NOTE: overwritten by `actor_global_plan_node`; max. distance from an obstacle at which costs are incurred for planning paths.
  cost_scaling_factor: 10  # exponential rate at which the obstacle cost drops off (default 10)