base_local_planner: dwa_local_planner/DWAPlannerROS

DWAPlannerROS:
  # Robot Configuration Parameters
  acc_lim_x: 2.5
  acc_lim_theta: 3.2
  acc_lim_y: 0.0

  max_vel_x: 1.5
  min_vel_x: 0.0

  max_vel_y: 0.0
  min_vel_y: 0.0

  # The velocity when robot is moving in a straight line
  max_vel_trans: 1.5
  min_vel_trans: 0.1

  max_vel_theta: 2.0
  min_vel_theta: 0.4

  # Forward Simulation Parameters
  sim_time: 2.0
  sim_granularity: 0.025 #

  # Trajectory Scoring Parameters
  goal_distance_bias: 20.0
  path_distance_bias: 32.0
  occdist_scale: 0.02

  stop_time_buffer: 0.2
  oscillation_reset_dist: 0.05

  forward_point_distance: 0.325

  scaling_speed: 0.25
  max_scaling_factor: 0.2

  vx_samples: 20
  vy_samples: 0
  vtheta_samples: 40

  controller_frequency: 10.0
  sim_period: 0.1 #

  # Goal Tolerance Parameters
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false

  theta_stopped_vel: 0.01 #
  trans_stopped_vel: 0.01 #

  # Debugging
  meter_scoring: true #
  publish_traj_pc : true
  publish_cost_grid_pc: true